function events(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',lc='.cache.html',$='/',$b='0D703654C607C4D5010CEBD6FDD18FC8',_b='242AB5F7C14C1342ABB8439CD8E62A54',ac='4102F784AA89AD2A59B25A9D69B6B12D',bc='4A4731B9FBF4B1401C0C3CC21426A45E',cc='5863FD17DF65CF5F1EC0DAB977765D2B',dc='5AE108B1624EA18DC68C0A2C75EACC82',ec='5F9759FD08FE91A0907A2C5100C0368C',fc='6710CBB001095DDB5DEAA1A8C1612D36',gc='9FA9CA69F03339F66BD0148FD722747F',kc=':',nb='::',tc='<script defer="defer">events.onInjectionDone(\'events\')<\/script>',gb='<script id="',qb='=',Z='?',hc='AA5777C4AB53465980D9878AD3961F70',Nb='ActiveXObject',sb='Bad handler "',ic='C17A5F68BD2E97F33B0D1C3620D0CE95',jc='CED02FBB33C49B5FAF37A8B7FC0AE6E1',Ob='ChromeTab.ChromeFrame',sc='DOMContentLoaded',Eb='Gears.Factory',ib='SCRIPT',fb='__gwt_marker_events',Gb='application/x-googlegears',jb='base',bb='baseUrl',S='begin',R='bootstrap',Mb='chromeframe',ab='clear.cache.gif',pb='content',X='end',P='events',db='events.nocache.js',mb='events::',Bb='function',Db='gears',Ub='gecko',Vb='gecko1_8',Ab='geolocation.api',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',mc='gwt/clean/clean.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',rc='head',Yb='hosted.html?events',qc='href',Cb='html5',Tb='ie6',Sb='ie8',Rb='ie9',Fb='ie_mobile',wb='iframe',_='img',xb="javascript:''",nc='link',Xb='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Qb='msie',lb='name',Ib='none',Hb='object',Kb='opera',yb='position:absolute;width:0;height:0;border:none',oc='rel',Pb='safari',cb='script',Zb='selectingPermutation',Q='startup',pc='stylesheet',eb='undefined',Wb='unknown',Jb='user.agent',Lb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}events=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){if(typeof navigator.geolocation!=eb&&typeof navigator.geolocation.getCurrentPosition==Bb){return Cb}if(window.google&&google.gears){return Db}var b=null;if(typeof GearsFactory!=eb){b=new GearsFactory}else{try{b=new ActiveXObject(Eb);if(b.getBuildInfo().indexOf(Fb)!=-1){b.privateSetGlobalObject(this)}}catch(a){if(typeof navigator.mimeTypes!=eb&&navigator.mimeTypes[Gb]){b=document.createElement(Hb);b.style.display=Ib;b.width=0;b.height=0;b.type=Gb;document.documentElement.appendChild(b)}}}if(!b){return Cb}if(!window.google){google={}}if(!google.gears){google.gears={factory:b}}return Db};u[Ab]={gears:0,html5:1};v[Jb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(Kb)!=-1}())return Kb;if(function(){return c.indexOf(Lb)!=-1||function(){if(c.indexOf(Mb)!=-1){return true}if(typeof window[Nb]!=eb){try{var b=new ActiveXObject(Ob);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Pb;if(function(){return c.indexOf(Qb)!=-1&&m.documentMode>=9}())return Rb;if(function(){return c.indexOf(Qb)!=-1&&m.documentMode>=8}())return Sb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Tb;if(function(){return c.indexOf(Ub)!=-1}())return Vb;return Wb};u[Jb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};events.onScriptLoad=function(){if(H){q=true;B()}};events.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Xb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Yb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Zb});if(!A()){try{F([Cb,Pb],$b);F([Cb,Tb],_b);F([Db,Pb],ac);F([Cb,Sb],bc);F([Cb,Kb],cc);F([Cb,Vb],dc);F([Db,Tb],ec);F([Db,Sb],fc);F([Db,Kb],gc);F([Cb,Rb],hc);F([Db,Rb],ic);F([Db,Vb],jc);J=w[G(Ab)][G(Jb)];var L=J.indexOf(kc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+lc}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[mc]){var a=m.createElement(nc);__gwt_stylesLoaded[mc]=a;a.setAttribute(oc,pc);a.setAttribute(qc,s+mc);m.getElementsByTagName(rc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(sc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(sc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Xb,millis:(new Date).getTime(),type:S});m.write(tc)}
events();